// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | FeatureGridV2Slice
  | EyebrowSlice
  | BentoGridSlice
  | CtaSectionSlice
  | HeroSystemSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *BentoGrid → Default → Primary → cards*
 */
export interface BentoGridSliceDefaultPrimaryCardsItem {
  /**
   * Title field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Icon field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: spark
   * - **API ID Path**: bento_grid.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "spark" | "shield" | "bolt" | "wand" | "grid" | "chat",
    "filled"
  >;

  /**
   * Size field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: bento_grid.default.primary.cards[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"md" | "sm" | "lg" | "xl", "filled">;

  /**
   * Emphasis field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: bento_grid.default.primary.cards[].emphasis
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  emphasis: prismic.SelectField<"normal" | "highlight">;

  /**
   * Link field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link Label field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Primary content in *BentoGrid → Default → Primary*
 */
export interface BentoGridSliceDefaultPrimary {
  /**
   * Eyebrow field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: 1
   * - **API ID Path**: bento_grid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;

  /**
   * Visual Mode field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: bento_grid.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"glass" | "gradient_orb">;

  /**
   * cards field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<BentoGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for BentoGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BentoGrid*
 */
type BentoGridSliceVariation = BentoGridSliceDefault;

/**
 * BentoGrid Shared Slice
 *
 * - **API ID**: `bento_grid`
 * - **Description**: BentoGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSlice = prismic.SharedSlice<
  "bento_grid",
  BentoGridSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Eyebrow field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: READY TO MOVE FASTER
   * - **API ID Path**: cta_section.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Let's Build your operating system.
   * - **API ID Path**: cta_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA Label field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Start s project
   * - **API ID Path**: cta_section.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See How it Works
   * - **API ID Path**: cta_section.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Visual Mode field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: glass
   * - **API ID Path**: cta_section.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"glass" | "gradient_orb", "filled">;

  /**
   * Emphasis field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: normal
   * - **API ID Path**: cta_section.default.primary.emphasis
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  emphasis: prismic.SelectField<"normal" | "strong", "filled">;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Item in *FeatureGrid → Default → Primary → Feature Cards*
 */
export interface EyebrowSliceDefaultPrimaryFeatureCardsItem {
  /**
   * Icons field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: star
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].icons
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icons: prismic.SelectField<"star" | "spark" | "shield" | "wand", "filled">;

  /**
   * Title field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Highlight field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface EyebrowSliceDefaultPrimary {
  /**
   * Eyebrow field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: 2
   * - **API ID Path**: eyebrow.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * Icon Style field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.icon_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_style: prismic.SelectField<"chip" | "none">;

  /**
   * Highlight Enabled field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: eyebrow.default.primary.highlight_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: glass
   * - **API ID Path**: eyebrow.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<
    "glass" | "gradient_orb" | "helix_3d",
    "filled"
  >;

  /**
   * Feature Cards field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: eyebrow.default.primary.feature_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_cards: prismic.GroupField<
    Simplify<EyebrowSliceDefaultPrimaryFeatureCardsItem>
  >;
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EyebrowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EyebrowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureGrid*
 */
type EyebrowSliceVariation = EyebrowSliceDefault;

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `eyebrow`
 * - **Description**: Eyebrow
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EyebrowSlice = prismic.SharedSlice<
  "eyebrow",
  EyebrowSliceVariation
>;

/**
 * Item in *FeatureGridV2 → Default → Primary → Cards*
 */
export interface FeatureGridV2SliceDefaultPrimaryCardsItem {
  /**
   * Icons field in *FeatureGridV2 → Default → Primary → Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_v2.default.primary.cards[].icons
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icons: prismic.SelectField<"star" | "spark" | "shield" | "wand">;

  /**
   * Title field in *FeatureGridV2 → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_v2.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureGridV2 → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: body
   * - **API ID Path**: feature_grid_v2.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Highlight field in *FeatureGridV2 → Default → Primary → Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: feature_grid_v2.default.primary.cards[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Primary content in *FeatureGridV2 → Default → Primary*
 */
export interface FeatureGridV2SliceDefaultPrimary {
  /**
   * Headline field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We build your business an Operating System.
   * - **API ID Path**: feature_grid_v2.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Eyebrow field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Features: Online
   * - **API ID Path**: feature_grid_v2.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Body field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: High-performance websites seamlessly connected to your daily workflow — powered by HelixFlow.
   * - **API ID Path**: feature_grid_v2.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * columns field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: feature_grid_v2.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;

  /**
   * Icon Style field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: chip
   * - **API ID Path**: feature_grid_v2.default.primary.icon_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_style: prismic.SelectField<"chip" | "none", "filled">;

  /**
   * Highlight Enabled field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: feature_grid_v2.default.primary.highlight_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_v2.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"glass" | "gradient_orb" | "3d_helix">;

  /**
   * Cards field in *FeatureGridV2 → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid_v2.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<FeatureGridV2SliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for FeatureGridV2 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridV2SliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridV2SliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureGridV2*
 */
type FeatureGridV2SliceVariation = FeatureGridV2SliceDefault;

/**
 * FeatureGridV2 Shared Slice
 *
 * - **API ID**: `feature_grid_v2`
 * - **Description**: FeatureGridV2
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridV2Slice = prismic.SharedSlice<
  "feature_grid_v2",
  FeatureGridV2SliceVariation
>;

/**
 * Primary content in *HeroSystem → Default → Primary*
 */
export interface HeroSystemSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: FROM WEBSITE TO OPERATING SYSTEM
   * - **API ID Path**: hero_system.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * HEADLINE field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Build Once. Operate Everything.
   * - **API ID Path**: hero_system.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Subheadline field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: High-performance websites seamlessly connected to your daily workflow — powered by HelixFlow.
   * - **API ID Path**: hero_system.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Primary CTA Label field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Start a Project
   * - **API ID Path**: hero_system.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_system.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See the System
   * - **API ID Path**: hero_system.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_system.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Badge Enabled field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_system.default.primary.badge_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  badge_enabled: prismic.BooleanField;

  /**
   * Badge Text field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digital Operations, built in.
   * - **API ID Path**: hero_system.default.primary.badge_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge_text: prismic.KeyTextField;

  /**
   * Visual Mode field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: helix_3d
   * - **API ID Path**: hero_system.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"helix_3d" | "gradient_orb", "filled">;
}

/**
 * Default variation for HeroSystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSystemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSystem*
 */
type HeroSystemSliceVariation = HeroSystemSliceDefault;

/**
 * HeroSystem Shared Slice
 *
 * - **API ID**: `hero_system`
 * - **Description**: HeroSystem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSystemSlice = prismic.SharedSlice<
  "hero_system",
  HeroSystemSliceVariation
>;

/**
 * Item in *IconList → Default → Primary → Items*
 */
export interface IconListSliceDefaultPrimaryItemsItem {
  /**
   * Item Icon field in *IconList → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: check
   * - **API ID Path**: icon_list.default.primary.items[].item_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  item_icon: prismic.SelectField<
    "check" | "sparkles" | "bolt" | "shield" | "star" | "info" | "warning",
    "filled"
  >;

  /**
   * Item Title field in *IconList → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.items[].item_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_title: prismic.KeyTextField;

  /**
   * Item Description field in *IconList → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.items[].item_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_description: prismic.RichTextField;

  /**
   * Item Is Highlighted field in *IconList → Default → Primary → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: icon_list.default.primary.items[].item_is_highlighted
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  item_is_highlighted: prismic.BooleanField;

  /**
   * Item Badge field in *IconList → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.items[].item_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item_badge: prismic.KeyTextField;
}

/**
 * Primary content in *IconList → Default → Primary*
 */
export interface IconListSliceDefaultPrimary {
  /**
   * Is Enabled field in *IconList → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: icon_list.default.primary.is_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *IconList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"none" | "gradient_orb" | "helix_3d">;

  /**
   * Section Padding field in *IconList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: icon_list.default.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  section_padding: prismic.SelectField<"md" | "sm" | "lg" | "none", "filled">;

  /**
   * Container Width field in *IconList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.container_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  container_width: prismic.SelectField<"standard" | "wide" | "full">;

  /**
   * Align Mode field in *IconList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: left
   * - **API ID Path**: icon_list.default.primary.align_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  align_mode: prismic.SelectField<"left" | "center", "filled">;

  /**
   * Density Mode field in *IconList → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: relaxed
   * - **API ID Path**: icon_list.default.primary.density_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  density_mode: prismic.SelectField<"relaxed" | "compact", "filled">;

  /**
   * Eyebrow field in *IconList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: icon_list.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *IconList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Headline
   * - **API ID Path**: icon_list.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *IconList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body
   * - **API ID Path**: icon_list.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Items field in *IconList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_list.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<IconListSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for IconList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconList*
 */
type IconListSliceVariation = IconListSliceDefault;

/**
 * IconList Shared Slice
 *
 * - **API ID**: `icon_list`
 * - **Description**: IconList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconListSlice = prismic.SharedSlice<
  "icon_list",
  IconListSliceVariation
>;

/**
 * Primary content in *SectionIntro → Default → Primary*
 */
export interface SectionIntroSliceDefaultPrimary {
  /**
   * Is Enabled field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: section_intro.default.primary.is_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: none
   * - **API ID Path**: section_intro.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<
    "none" | "gradient_orb" | "helix_3d",
    "filled"
  >;

  /**
   * Section Padding field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: section_intro.default.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  section_padding: prismic.SelectField<"md" | "sm" | "none" | "lg", "filled">;

  /**
   * Container Width field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: standard
   * - **API ID Path**: section_intro.default.primary.container_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  container_width: prismic.SelectField<"standard" | "wide" | "full", "filled">;

  /**
   * Align Mode field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: section_intro.default.primary.align_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  align_mode: prismic.SelectField<"left" | "center">;

  /**
   * Eyebrow field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: section_intro.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Headline
   * - **API ID Path**: section_intro.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *SectionIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body
   * - **API ID Path**: section_intro.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for SectionIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionIntro*
 */
type SectionIntroSliceVariation = SectionIntroSliceDefault;

/**
 * SectionIntro Shared Slice
 *
 * - **API ID**: `section_intro`
 * - **Description**: SectionIntro
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionIntroSlice = prismic.SharedSlice<
  "section_intro",
  SectionIntroSliceVariation
>;

/**
 * Item in *StepsTimeline → Default → Primary → Steps*
 */
export interface StepsTimelineSliceDefaultPrimaryStepsItem {
  /**
   * Step Title field in *StepsTimeline → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: steps_timeline.default.primary.steps[].step_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_title: prismic.KeyTextField;

  /**
   * Step Body field in *StepsTimeline → Default → Primary → Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: none
   * - **API ID Path**: steps_timeline.default.primary.steps[].step_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  step_body: prismic.RichTextField;

  /**
   * Step Icon field in *StepsTimeline → Default → Primary → Steps*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: check
   * - **API ID Path**: steps_timeline.default.primary.steps[].step_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  step_icon: prismic.SelectField<
    "check" | " shield" | "sparkles" | "bolt" | "star" | "info" | "warning",
    "filled"
  >;

  /**
   * Step Is Highlighted field in *StepsTimeline → Default → Primary → Steps*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: steps_timeline.default.primary.steps[].step_is_highlighted
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  step_is_highlighted: prismic.BooleanField;

  /**
   * Step Badge field in *StepsTimeline → Default → Primary → Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: steps_timeline.default.primary.steps[].step_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  step_badge: prismic.KeyTextField;
}

/**
 * Primary content in *StepsTimeline → Default → Primary*
 */
export interface StepsTimelineSliceDefaultPrimary {
  /**
   * Is Enabled field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: steps_timeline.default.primary.is_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: none
   * - **API ID Path**: steps_timeline.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<
    "none" | "gradient_orb" | "3d_helix",
    "filled"
  >;

  /**
   * Section Padding field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: steps_timeline.default.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  section_padding: prismic.SelectField<"md" | "sm" | "lg" | "none", "filled">;

  /**
   * Container Width field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: standard
   * - **API ID Path**: steps_timeline.default.primary.container_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  container_width: prismic.SelectField<"standard" | " wide" | "full", "filled">;

  /**
   * Align Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: left
   * - **API ID Path**: steps_timeline.default.primary.align_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  align_mode: prismic.SelectField<"left" | "center", "filled">;

  /**
   * Density Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: relaxed
   * - **API ID Path**: steps_timeline.default.primary.density_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  density_mode: prismic.SelectField<"relaxed" | "compact", "filled">;

  /**
   * Animation Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: none
   * - **API ID Path**: steps_timeline.default.primary.animation_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  animation_mode: prismic.SelectField<
    "none" | "fade_in" | "slide_up" | "stagger",
    "filled"
  >;

  /**
   * Layout Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: vertical
   * - **API ID Path**: steps_timeline.default.primary.layout_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout_mode: prismic.SelectField<"vertical" | "horizontal", "filled">;

  /**
   * Connector Mode field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: line
   * - **API ID Path**: steps_timeline.default.primary.connector_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  connector_mode: prismic.SelectField<"line" | "dots" | "none", "filled">;

  /**
   * Number Style field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: numeric
   * - **API ID Path**: steps_timeline.default.primary.number_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  number_style: prismic.SelectField<"numeric" | "icon", "filled">;

  /**
   * Eyebrow field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: steps_timeline.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Headline
   * - **API ID Path**: steps_timeline.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: none
   * - **API ID Path**: steps_timeline.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Steps field in *StepsTimeline → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: steps_timeline.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  steps: prismic.GroupField<
    Simplify<StepsTimelineSliceDefaultPrimaryStepsItem>
  >;
}

/**
 * Default variation for StepsTimeline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepsTimelineSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StepsTimelineSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StepsTimeline*
 */
type StepsTimelineSliceVariation = StepsTimelineSliceDefault;

/**
 * StepsTimeline Shared Slice
 *
 * - **API ID**: `steps_timeline`
 * - **Description**: StepsTimeline
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StepsTimelineSlice = prismic.SharedSlice<
  "steps_timeline",
  StepsTimelineSliceVariation
>;

/**
 * Item in *TabsSection → Default → Primary → Tabs*
 */
export interface TabsSectionSliceDefaultPrimaryTabsItem {
  /**
   * Tab Label field in *TabsSection → Default → Primary → Tabs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Label
   * - **API ID Path**: tabs_section.default.primary.tabs[].tab_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tab_label: prismic.KeyTextField;

  /**
   * Tab Icon field in *TabsSection → Default → Primary → Tabs*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: check
   * - **API ID Path**: tabs_section.default.primary.tabs[].tab_icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tab_icon: prismic.SelectField<
    "check" | "sparkles" | "bolt" | "shield" | "star" | "info" | "warning",
    "filled"
  >;

  /**
   * Tab Badge field in *TabsSection → Default → Primary → Tabs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Badge
   * - **API ID Path**: tabs_section.default.primary.tabs[].tab_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tab_badge: prismic.KeyTextField;

  /**
   * Tab Body field in *TabsSection → Default → Primary → Tabs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body
   * - **API ID Path**: tabs_section.default.primary.tabs[].tab_body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  tab_body: prismic.RichTextField;
}

/**
 * Primary content in *TabsSection → Default → Primary*
 */
export interface TabsSectionSliceDefaultPrimary {
  /**
   * Is Enabled field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: tabs_section.default.primary.is_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: none
   * - **API ID Path**: tabs_section.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<
    "none" | "gradient_orb" | "3d_helix",
    "filled"
  >;

  /**
   * Section Padding field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: tabs_section.default.primary.section_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  section_padding: prismic.SelectField<"md" | "sm" | "lg" | "none", "filled">;

  /**
   * Container Width field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: standard
   * - **API ID Path**: tabs_section.default.primary.container_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  container_width: prismic.SelectField<"standard" | "wide" | "full", "filled">;

  /**
   * Align Mode field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: left
   * - **API ID Path**: tabs_section.default.primary.align_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  align_mode: prismic.SelectField<"left" | "center", "filled">;

  /**
   * Density Mode field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: relaxed
   * - **API ID Path**: tabs_section.default.primary.density_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  density_mode: prismic.SelectField<"relaxed" | "compact", "filled">;

  /**
   * Animation Mode field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: none
   * - **API ID Path**: tabs_section.default.primary.animation_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  animation_mode: prismic.SelectField<
    "none" | "slide_up" | "stagger" | "fade_in",
    "filled"
  >;

  /**
   * Tabs Style field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: pills
   * - **API ID Path**: tabs_section.default.primary.tabs_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  tabs_style: prismic.SelectField<"pills" | "underline" | "cards", "filled">;

  /**
   * Content Style field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: panel
   * - **API ID Path**: tabs_section.default.primary.content_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content_style: prismic.SelectField<"panel" | "grid", "filled">;

  /**
   * Default Tab Index field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 0
   * - **API ID Path**: tabs_section.default.primary.default_tab_index
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  default_tab_index: prismic.NumberField;

  /**
   * Show Icons field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: tabs_section.default.primary.show_icons
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_icons: prismic.BooleanField;

  /**
   * Allow Wrap field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: tabs_section.default.primary.allow_wrap
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  allow_wrap: prismic.BooleanField;

  /**
   * Eyebrow field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: tabs_section.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Headline
   * - **API ID Path**: tabs_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Body
   * - **API ID Path**: tabs_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Tabs field in *TabsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: tabs_section.default.primary.tabs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tabs: prismic.GroupField<Simplify<TabsSectionSliceDefaultPrimaryTabsItem>>;
}

/**
 * Default variation for TabsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TabsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TabsSection*
 */
type TabsSectionSliceVariation = TabsSectionSliceDefault;

/**
 * TabsSection Shared Slice
 *
 * - **API ID**: `tabs_section`
 * - **Description**: TabsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TabsSectionSlice = prismic.SharedSlice<
  "tabs_section",
  TabsSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BentoGridSlice,
      BentoGridSliceDefaultPrimaryCardsItem,
      BentoGridSliceDefaultPrimary,
      BentoGridSliceVariation,
      BentoGridSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      EyebrowSlice,
      EyebrowSliceDefaultPrimaryFeatureCardsItem,
      EyebrowSliceDefaultPrimary,
      EyebrowSliceVariation,
      EyebrowSliceDefault,
      FeatureGridV2Slice,
      FeatureGridV2SliceDefaultPrimaryCardsItem,
      FeatureGridV2SliceDefaultPrimary,
      FeatureGridV2SliceVariation,
      FeatureGridV2SliceDefault,
      HeroSystemSlice,
      HeroSystemSliceDefaultPrimary,
      HeroSystemSliceVariation,
      HeroSystemSliceDefault,
      IconListSlice,
      IconListSliceDefaultPrimaryItemsItem,
      IconListSliceDefaultPrimary,
      IconListSliceVariation,
      IconListSliceDefault,
      SectionIntroSlice,
      SectionIntroSliceDefaultPrimary,
      SectionIntroSliceVariation,
      SectionIntroSliceDefault,
      StepsTimelineSlice,
      StepsTimelineSliceDefaultPrimaryStepsItem,
      StepsTimelineSliceDefaultPrimary,
      StepsTimelineSliceVariation,
      StepsTimelineSliceDefault,
      TabsSectionSlice,
      TabsSectionSliceDefaultPrimaryTabsItem,
      TabsSectionSliceDefaultPrimary,
      TabsSectionSliceVariation,
      TabsSectionSliceDefault,
    };
  }
}
