// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *BentoGrid → Default → Primary → cards*
 */
export interface BentoGridSliceDefaultPrimaryCardsItem {
  /**
   * Title field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Icon field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: spark
   * - **API ID Path**: bento_grid.default.primary.cards[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "spark" | "shield" | "bolt" | "wand" | "grid" | "chat",
    "filled"
  >;

  /**
   * Size field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: md
   * - **API ID Path**: bento_grid.default.primary.cards[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"md" | "sm" | "lg" | "xl", "filled">;

  /**
   * Emphasis field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: bento_grid.default.primary.cards[].emphasis
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  emphasis: prismic.SelectField<"normal" | "highlight">;

  /**
   * Link field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link Label field in *BentoGrid → Default → Primary → cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[].link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Primary content in *BentoGrid → Default → Primary*
 */
export interface BentoGridSliceDefaultPrimary {
  /**
   * Eyebrow field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: 1
   * - **API ID Path**: bento_grid.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"1" | "2" | "3" | "4", "filled">;

  /**
   * Visual Mode field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: bento_grid.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"glass" | "gradient_orb">;

  /**
   * cards field in *BentoGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<BentoGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for BentoGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BentoGrid*
 */
type BentoGridSliceVariation = BentoGridSliceDefault;

/**
 * BentoGrid Shared Slice
 *
 * - **API ID**: `bento_grid`
 * - **Description**: BentoGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoGridSlice = prismic.SharedSlice<
  "bento_grid",
  BentoGridSliceVariation
>;

/**
 * Primary content in *CtaSection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Eyebrow field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: READY TO MOVE FASTER
   * - **API ID Path**: cta_section.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Let's Build your operating system.
   * - **API ID Path**: cta_section.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA Label field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Start s project
   * - **API ID Path**: cta_section.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See How it Works
   * - **API ID Path**: cta_section.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Visual Mode field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: glass
   * - **API ID Path**: cta_section.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"glass" | "gradient_orb", "filled">;

  /**
   * Emphasis field in *CtaSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: normal
   * - **API ID Path**: cta_section.default.primary.emphasis
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  emphasis: prismic.SelectField<"normal" | "strong", "filled">;
}

/**
 * Default variation for CtaSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaSection*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaSection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Item in *FeatureGrid → Default → Primary → Feature Cards*
 */
export interface EyebrowSliceDefaultPrimaryFeatureCardsItem {
  /**
   * Icons field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: star
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].icons
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icons: prismic.SelectField<"star" | "spark" | "shield" | "wand", "filled">;

  /**
   * Title field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Highlight field in *FeatureGrid → Default → Primary → Feature Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: eyebrow.default.primary.feature_cards[].highlight
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight: prismic.BooleanField;
}

/**
 * Primary content in *FeatureGrid → Default → Primary*
 */
export interface EyebrowSliceDefaultPrimary {
  /**
   * Eyebrow field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Headline field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Body field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Columns field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: 2
   * - **API ID Path**: eyebrow.default.primary.columns
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  columns: prismic.SelectField<"2" | "3" | "4", "filled">;

  /**
   * Icon Style field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **API ID Path**: eyebrow.default.primary.icon_style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_style: prismic.SelectField<"chip" | "none">;

  /**
   * Highlight Enabled field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: eyebrow.default.primary.highlight_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  highlight_enabled: prismic.BooleanField;

  /**
   * Visual Mode field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: glass
   * - **API ID Path**: eyebrow.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<
    "glass" | "gradient_orb" | "helix_3d",
    "filled"
  >;

  /**
   * Feature Cards field in *FeatureGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: eyebrow.default.primary.feature_cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_cards: prismic.GroupField<
    Simplify<EyebrowSliceDefaultPrimaryFeatureCardsItem>
  >;
}

/**
 * Default variation for FeatureGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EyebrowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EyebrowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeatureGrid*
 */
type EyebrowSliceVariation = EyebrowSliceDefault;

/**
 * FeatureGrid Shared Slice
 *
 * - **API ID**: `eyebrow`
 * - **Description**: Eyebrow
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EyebrowSlice = prismic.SharedSlice<
  "eyebrow",
  EyebrowSliceVariation
>;

/**
 * Primary content in *HeroSystem → Default → Primary*
 */
export interface HeroSystemSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: FROM WEBSITE TO OPERATING SYSTEM
   * - **API ID Path**: hero_system.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * HEADLINE field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Build Once. Operate Everything.
   * - **API ID Path**: hero_system.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Subheadline field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: High-performance websites seamlessly connected to your daily workflow — powered by HelixFlow.
   * - **API ID Path**: hero_system.default.primary.subheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Primary CTA Label field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Start a Project
   * - **API ID Path**: hero_system.default.primary.primary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_cta_label: prismic.KeyTextField;

  /**
   * Primary CTA Link field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_system.default.primary.primary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA Label field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: See the System
   * - **API ID Path**: hero_system.default.primary.secondary_cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_cta_label: prismic.KeyTextField;

  /**
   * Secondary CTA Link field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_system.default.primary.secondary_cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Badge Enabled field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_system.default.primary.badge_enabled
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  badge_enabled: prismic.BooleanField;

  /**
   * Badge Text field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Digital Operations, built in.
   * - **API ID Path**: hero_system.default.primary.badge_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge_text: prismic.KeyTextField;

  /**
   * Visual Mode field in *HeroSystem → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: none
   * - **Default Value**: helix_3d
   * - **API ID Path**: hero_system.default.primary.visual_mode
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  visual_mode: prismic.SelectField<"helix_3d" | "gradient_orb", "filled">;
}

/**
 * Default variation for HeroSystem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSystemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSystemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSystem*
 */
type HeroSystemSliceVariation = HeroSystemSliceDefault;

/**
 * HeroSystem Shared Slice
 *
 * - **API ID**: `hero_system`
 * - **Description**: HeroSystem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSystemSlice = prismic.SharedSlice<
  "hero_system",
  HeroSystemSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.WriteClientConfig,
    ): prismic.WriteClient;
  }

  interface CreateMigration {
    (): prismic.Migration;
  }

  namespace Content {
    export type {
      BentoGridSlice,
      BentoGridSliceDefaultPrimaryCardsItem,
      BentoGridSliceDefaultPrimary,
      BentoGridSliceVariation,
      BentoGridSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      EyebrowSlice,
      EyebrowSliceDefaultPrimaryFeatureCardsItem,
      EyebrowSliceDefaultPrimary,
      EyebrowSliceVariation,
      EyebrowSliceDefault,
      HeroSystemSlice,
      HeroSystemSliceDefaultPrimary,
      HeroSystemSliceVariation,
      HeroSystemSliceDefault,
    };
  }
}
